import { FoliosData } from "./types";
import { mockPassportData } from "../passport/mockData";

export const mockFoliosData: FoliosData = {
  folios: [
    {
      id: "folio-1",
      roleTitle: "Senior Frontend Engineer",
      department: "Engineering",
      requiredSkills: ["React", "TypeScript", "CSS", "Performance Optimization"],
      experienceRange: [5, 8],
      status: "active",
      createdDate: "2025-10-15",
      candidateIds: ["cand-1", "cand-2", "cand-3"],
    },
    {
      id: "folio-2",
      roleTitle: "Full-Stack Developer",
      department: "Product",
      requiredSkills: ["Node.js", "React", "PostgreSQL", "AWS"],
      experienceRange: [3, 6],
      status: "active",
      createdDate: "2025-10-28",
      candidateIds: ["cand-1", "cand-4"],
    },
    {
      id: "folio-3",
      roleTitle: "Design System Lead",
      department: "Design",
      requiredSkills: ["Design Systems", "React", "Figma", "Accessibility"],
      experienceRange: [4, 7],
      status: "draft",
      createdDate: "2025-11-01",
      candidateIds: [],
    },
  ],
  candidates: [
    {
      id: "cand-1",
      name: "Jordan Smith",
      headline: "Full-stack engineer passionate about clean code and UX",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan",
      skills: ["React", "TypeScript", "Node.js", "AWS", "PostgreSQL"],
      keySkills: ["React", "TypeScript", "Node.js", "AWS"],
      passportData: mockPassportData,
    },
    {
      id: "cand-2",
      name: "Alex Chen",
      headline: "Frontend specialist with focus on performance",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
      skills: ["React", "Vue.js", "Webpack", "Performance Optimization", "Testing"],
      keySkills: ["React", "Vue", "Webpack", "Performance"],
      passportData: {
        ...mockPassportData,
        personalSummary: "Frontend engineer with 6 years of experience building high-performance web applications.",
        keySkills: ["React", "Vue.js", "Webpack", "Performance Optimization", "Testing"],
      },
    },
    {
      id: "cand-3",
      name: "Sam Rodriguez",
      headline: "Creative developer bridging design and engineering",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sam",
      skills: ["React", "CSS/SCSS", "Motion Design", "Accessibility", "Figma"],
      keySkills: ["React", "CSS", "Animation", "Figma"],
      passportData: {
        ...mockPassportData,
        personalSummary: "Creative frontend developer with a passion for beautiful, accessible interfaces.",
        keySkills: ["React", "CSS/SCSS", "Motion Design", "Accessibility", "Figma"],
      },
    },
    {
      id: "cand-4",
      name: "Taylor Kim",
      headline: "Backend-focused full-stack with DevOps expertise",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor",
      skills: ["Node.js", "PostgreSQL", "Docker", "Kubernetes", "AWS"],
      keySkills: ["Node.js", "PostgreSQL", "Docker", "AWS"],
      passportData: {
        ...mockPassportData,
        personalSummary: "Full-stack developer specializing in scalable backend systems and cloud infrastructure.",
        keySkills: ["Node.js", "PostgreSQL", "Docker", "Kubernetes", "AWS"],
      },
    },
  ],
  annotations: {
    "folio-1-cand-1": {
      candidateId: "cand-1",
      folioId: "folio-1",
      tags: ["shortlist", "annotated"],
      notes: "Strong technical background. Great fit for senior role. Schedule technical interview.",
      reviewedDate: "2025-10-20",
    },
    "folio-1-cand-2": {
      candidateId: "cand-2",
      folioId: "folio-1",
      tags: ["neutral"],
      notes: "Good frontend skills but limited full-stack experience.",
      reviewedDate: "2025-10-21",
    },
  },
};

export const availableSkills = [
  "React",
  "TypeScript",
  "JavaScript",
  "Node.js",
  "Python",
  "Java",
  "Go",
  "PostgreSQL",
  "MongoDB",
  "AWS",
  "Docker",
  "Kubernetes",
  "GraphQL",
  "REST API",
  "CSS/SCSS",
  "Tailwind",
  "Vue.js",
  "Angular",
  "Next.js",
  "Express",
  "Figma",
  "Design Systems",
  "Accessibility",
  "Testing",
  "CI/CD",
  "Performance Optimization",
  "Security",
  "Machine Learning",
  "Data Science",
];

export const departments = [
  "Engineering",
  "Product",
  "Design",
  "Data Science",
  "DevOps",
  "Security",
  "Marketing",
  "Sales",
  "Operations",
];
